<a href="https://colab.research.google.com/github/SumitBhatt061/Reinforcement-learning/blob/main/Q_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [49]:
#reward matrix
R=np.matrix([[-1,-1,-1,-1,0,-1],
             [-1,-1,-1,0,-1,100],
             [-1,-1,-1,0,-1,-1],
             [-1,0,0,-1,0,-1],
             [-1,0,0,-1,-1,100],
             [-1,0,-1,-1,0,100],
])

In [50]:
R

matrix([[ -1,  -1,  -1,  -1,   0,  -1],
        [ -1,  -1,  -1,   0,  -1, 100],
        [ -1,  -1,  -1,   0,  -1,  -1],
        [ -1,   0,   0,  -1,   0,  -1],
        [ -1,   0,   0,  -1,  -1, 100],
        [ -1,   0,  -1,  -1,   0, 100]])

In [51]:
#Q matrix
Q=np.matrix(np.zeros([6,6]))

In [52]:
print(Q)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [53]:
#gama- learning rate
gamma=0.8

In [54]:
  #initial state
  initial_state=1

In [55]:
#function to retuen all the available action in the sate given as an argument
def available_action(state):
  current_state_row=R[state,]
  av_act=np.where(current_state_row>=0)[1]
  return av_act

In [56]:
available_act=available_action(initial_state)

In [57]:
print(available_act)

[3 5]


In [58]:
def sample_next_action(available_act):
    next_action=int(np.random.choice(available_act, 1))
    return next_action


In [59]:
action=sample_next_action(available_act)

/tmp/ipython-input-2561883865.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  next_action=int(np.random.choice(available_act, 1))


In [60]:
print(action)

5


In [61]:
def update(current_state, action, gamma):
  max_index = np.where(Q[action,] == np.max(Q[action,]))[1]
  if max_index.shape[0] > 1:
     max_index = int(np.random.choice(max_index, size=1))
  else:
       max_index = int(max_index)
  max_value = Q[action, max_index]
  Q[current_state, action] = R[current_state, action] + gamma * max_value

update(initial_state, action, gamma)






/tmp/ipython-input-287471053.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  max_index = int(np.random.choice(max_index, size=1))


In [62]:
for i in range(10000):
    current_state=np.random.randint(0,int(Q.shape[0]))
    available_act=available_action(current_state)
    action=sample_next_action(available_act)
    update(current_state,action,gamma)

/tmp/ipython-input-2561883865.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  next_action=int(np.random.choice(available_act, 1))
/tmp/ipython-input-287471053.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  max_index = int(max_index)
/tmp/ipython-input-287471053.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  max_index = int(np.random.choice(max_index, size=1))


In [63]:
print(Q)

[[  0.   0.   0.   0. 400.   0.]
 [  0.   0.   0. 320.   0. 500.]
 [  0.   0.   0. 320.   0.   0.]
 [  0. 400. 256.   0. 400.   0.]
 [  0. 400. 256.   0.   0. 500.]
 [  0. 400.   0.   0. 400. 500.]]


In [64]:
print(Q/np.max(Q)*100)

[[  0.    0.    0.    0.   80.    0. ]
 [  0.    0.    0.   64.    0.  100. ]
 [  0.    0.    0.   64.    0.    0. ]
 [  0.   80.   51.2   0.   80.    0. ]
 [  0.   80.   51.2   0.    0.  100. ]
 [  0.   80.    0.    0.   80.  100. ]]


In [65]:
#test
current_state=2
steps=[current_state]

In [66]:
while current_state!=5:
  next_step_index=np.where(Q[current_state,]==np.max(Q[current_state,]))[1]
  if next_step_index.shape[0]>1:
    next_step_index=int(np.random.choice(next_step_index,size=1))
  else:
    next_step_index=int(next_step_index)
  steps.append(next_step_index)
  current_state=next_step_index

/tmp/ipython-input-2972407026.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  next_step_index=int(next_step_index)
/tmp/ipython-input-2972407026.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  next_step_index=int(np.random.choice(next_step_index,size=1))


In [67]:
print("path:\n",steps)

path:
 [2, 3, 4, 5]
